### ISSUE TITLE
Transformers lost somewhere

### ISSUE THREAD

**Issue by merqlove** [michalmuskala/env#4]
Nice idea!
But something wrong with transformers...

``` elixir
config :some_app, :redis,
  namespace: "some_app",
  host: "localhost",
  port: "6379"
```

``` elixir
transformer = fn
  [:port], value -> String.to_integer(value)
  _,       value -> value
end

{:ok, redis_config} = Env.fetch(:some_app, :redis, transformer: transformer)
IO.inspect redis_config
```

```
#> [namespace: "some_app", host: "localhost", port: "6379"]
```

**Comment by michalmuskala** [comment]
In this case they path will be `[:redis, :port]`, since this is the whole path. I'm not sure which way is better - including the key or not, so I'm open to suggestions.

**Comment by merqlove** [comment]
with one level configs, key including is too much, in my opinion.
but it is really useful if you parsing 2+ levels configuration.

so maybe [_, :port] will be workaround for this lite case?

**Comment by michalmuskala** [comment]
Yes, that would work as well. I'm just thinking if it makes sense to prepend the top-level key name all the time. It has the advantage that you could use the same transformer function for accessing all the various keys, instead of having a specialised one for each access.

**Comment by michalmuskala** [comment]
Since this is not really an issue - just the way it works, I'm going to close this.
